# Generated by Django 6.0 on 2025-12-25 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="email",
            field=models.EmailField(default="", max_length=100),
        ),
    ]
